### PR TITLE
Check for null pointers instead of relying on catch_unwind; address soundness issues

### LINKED ISSUE #4: LiveView Native Clients: Unblock JetPack
Investigation the way to avoid the wrong deallocation of the native pointers.

### PR DESCRIPTION
**Pull request by Bajix**
This PR address memory safety issues and removes all usage of catch_unwind and instead checks for null pointers and throws the appropriate exceptions. All functions that rely on raw pointers have been updated to be marked as unsafe

### CODE REVIEW

File: core/src/main/java/org/phoenixframework/liveview/lib/Document.kt [hunk 1]
```diff
@@ -1,17 +1,36 @@
...
+        }
+
+        private fun decRef(ref: Long) {
+            refCount[ref] = (refCount[ref] ?: 0) - 1
+            if ((refCount[ref] ?:0) <= 0) {
+                refCount.remove(ref)
+            }
+            Log.d("Document", "refCount = ${refCount.entries.sumOf { it.value }}")
+        }
+
```
Comment (KronicDeth) [inline core/src/main/java/org/phoenixframework/liveview/lib/Document.kt]: This isn't thread-safe.  There's no `synchronized` or explicit mutex.

**Review by KronicDeth — CHANGES_REQUESTED** [review]
The refcount functions need to be made thread safe

**Comment by nelson-glauber** [comment]
From the Android standpoint, it's working fine using my development branch of [LiveView-Client-Jetpack](https://github.com/liveview-native/liveview-client-jetpack/tree/add-elixir-platform-lib).

File: core/build.gradle [hunk 2]
```diff
@@ -61,3 +60,27 @@ afterEvaluate {
         }
     }
 }
+
+// Running cargo command before build
+tasks.configureEach { task ->
+    if ((task.name == 'javaPreCompileDebug' || task.name == 'javaPreCompileRelease')) {
+        task.dependsOn 'cargoBuild'
+    }
+}
```
Comment (KronicDeth) [inline core/build.gradle:69]: Cool, I didn't know I could do that to get multiple tasks patched. ❤️

File: core/src/main/java/org/phoenixframework/liveview/lib/Attribute.kt [hunk 3]
```diff
@@ -1,13 +1,16 @@
 package org.phoenixframework.liveview.lib
 
-class Attribute(private var nativeObject: Long) {
+class Attribute internal constructor(private var nativeObject: Long) {
```
Comment (KronicDeth) [inline core/src/main/java/org/phoenixframework/liveview/lib/Attribute.kt:3]: ❤️ Good privacy change!

File: core/src/main/java/org/phoenixframework/liveview/lib/Document.kt [hunk 4]
```diff
@@ -1,17 +1,25 @@
 package org.phoenixframework.liveview.lib
 
+
 class Document {
     private var nativeObject: Long
+    private var asBorrow: Boolean
```
Comment (KronicDeth) [inline core/src/main/java/org/phoenixframework/liveview/lib/Document.kt]: This can't change outside of the constructors, so it can be `val` instead of `var`

```suggestion
    private val asBorrow: Boolean
```

File: jni_bindings/src/lib.rs [hunk 5]
```diff
@@ -1,59 +1,55 @@
...
-    env.new_string(x).unwrap()
-}
-
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_drop(
-    _env: JNIEnv,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_drop(
+    mut env: JNIEnv,
     _: JClass,
+    // non-null raw pointer to Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:31]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.

```suggestion
    // raw pointer to Document
```

File: core/src/main/java/org/phoenixframework/liveview/lib/Document.kt [hunk 6]
```diff
@@ -128,20 +126,9 @@ class Document {
...
-    @Throws(Throwable::class)
     protected fun finalize() {
-        try {
-            delete()
-        } finally {
-            // do nothing
+        if (!asBorrow) {
+            drop(nativeObject)
         }
     }
```
Comment (KronicDeth) [inline core/src/main/java/org/phoenixframework/liveview/lib/Document.kt:133]: Doesn't this need to set `nativeObject = 0` like `delete` did, so `drop(nativeObject)`'s internal check for `this.is_null()` can work correctly in case some code calls `drop` twice?

File: core/src/main/java/org/phoenixframework/liveview/lib/JavaResult.kt [hunk 7]
```diff
@@ -1,6 +1,6 @@
 package org.phoenixframework.liveview.lib
 
-class JavaResult(private var nativeObject: Long) {
+internal class JavaResult(private var nativeObject: Long) {
```
Comment (KronicDeth) [inline core/src/main/java/org/phoenixframework/liveview/lib/JavaResult.kt:3]: ❤️ Privacy change.

File: core/src/main/java/org/phoenixframework/liveview/lib/JavaResult.kt [hunk 8]
```diff
@@ -16,23 +16,9 @@ class JavaResult(private var nativeObject: Long) {
...
+    private external fun drop(pointer: Long)
 
-    @Throws(Throwable::class)
     protected fun finalize() {
-        try {
-            delete()
-        } finally {
-            // do nothing
-        }
+        drop(nativeObject)
```
Comment (KronicDeth) [inline core/src/main/java/org/phoenixframework/liveview/lib/JavaResult.kt:22]: Doesn't this need to set `nativeObject = 0` like `delete` did, so `drop(nativeObject)`'s internal check for `this.is_null()` can work correctly in case some code calls `drop` twice?

File: core/src/main/java/org/phoenixframework/liveview/lib/Node.kt [hunk 9]
```diff
@@ -3,36 +3,47 @@ package org.phoenixframework.liveview.lib
...
+        private var nativeObject: Long
 
-        private external fun drop(pointer: Long)
+        internal constructor(pointer: Long) {
+            nativeObject = pointer
+        }
+
+        fun namespace(): String {
+            return get_namespace(nativeObject)
+        }
```
Comment (KronicDeth) [inline core/src/main/java/org/phoenixframework/liveview/lib/Node.kt]: This can remain a property with a getter defined

```suggestion
        val namespace: String
            get() = get_namespce(nativeOject)
```

File: core/src/main/java/org/phoenixframework/liveview/lib/Node.kt [hunk 10]
```diff
@@ -3,36 +3,47 @@ package org.phoenixframework.liveview.lib
...
+
+        fun tag(): String {
+            return get_tag(nativeObject)
+        }
```
Comment (KronicDeth) [inline core/src/main/java/org/phoenixframework/liveview/lib/Node.kt]: This can remain a property with a getter defined

```suggestion
        val tag: String
            get() = get_tag(nativeObject)
```

File: core/src/main/java/org/phoenixframework/liveview/lib/Node.kt [hunk 11]
```diff
@@ -3,36 +3,47 @@ package org.phoenixframework.liveview.lib
...
 
-        @Synchronized
-        private fun delete() {
-            if (nativeObject != 0L) {
-                drop(nativeObject)
-                nativeObject = 0
-            }
+        fun attributes(): Array<Attribute> {
+            return get_attributes(nativeObject)
         }
```
Comment (KronicDeth) [inline core/src/main/java/org/phoenixframework/liveview/lib/Node.kt]: This can remain a property with a getter defined

```suggestion
        val attributes(): Array<Attribute>
            get() = get_attributes(nativeObject)
```

File: core/src/main/java/org/phoenixframework/liveview/lib/Node.kt [hunk 12]
```diff
@@ -3,36 +3,47 @@ package org.phoenixframework.liveview.lib
...
+        private external fun drop(pointer: Long)
+
         protected fun finalize() {
-            try {
-                delete()
-            } finally {
-                // do nothing
-            }
+            drop(nativeObject)
         }
```
Comment (KronicDeth) [inline core/src/main/java/org/phoenixframework/liveview/lib/Node.kt:39]: Doesn't this need to set `nativeObject = 0` like `delete` did, so `drop(nativeObject)`'s internal check for `this.is_null()` can work correctly in case some code calls `drop` twice?

File: core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt [hunk 13]
```diff
@@ -0,0 +1,45 @@
...
+
+import org.junit.Test
+import org.junit.Assert.*
+import org.phoenixframework.liveview.lib.Document
+
+/**
+ * Example local unit test, which will execute on the development machine (host).
+ *
+ * See [testing documentation](http://d.android.com/tools/testing).
+ */
```
Comment (KronicDeth) [inline core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt]:
```suggestion
```

File: core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt [hunk 14]
```diff
@@ -0,0 +1,45 @@
...
+
+        var to = Document.parse("""
+        <VStack modifiers="">
+            <VStack>
+                <Text>Success! Check your email for magic link</Text>
+            </VStack>
+        </VStack>
+        """);
+
+        doc.merge(to,  Document.Companion.Handler());
```
Comment (KronicDeth) [inline core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt:38]: It's not obvious how this test can fail.  What would happen if merge didn't work?

File: core/src/test/java/org/phoenixframework/liveview_jetpack/ExampleUnitTest.kt [hunk 15]
```diff
@@ -1,17 +0,0 @@
-package org.phoenixframework.liveview_jetpack
```
Comment (KronicDeth) [inline core/src/test/java/org/phoenixframework/liveview_jetpack/ExampleUnitTest.kt:1]: ❤️

File: github.properties [hunk 16]
```diff
@@ -1,12 +0,0 @@
-## This file is automatically generated by Android Studio.
```
Comment (KronicDeth) [inline github.properties:1]: ❤️

File: jni_bindings/src/lib.rs [hunk 17]
```diff
@@ -73,159 +69,226 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_00024Comp
...
 }
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_JavaResult_drop<'local>(
-    _env: JNIEnv<'local>,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_JavaResult_drop<'local>(
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
-    j_result: jlong,
+    // non-null raw pointer to JavaResult
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:106]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.

```suggestion
    // raw pointer to JavaResult
```

File: jni_bindings/src/lib.rs [hunk 18]
```diff
@@ -73,159 +69,226 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_00024Comp
...
-// returns pointer to document else 0
+/// Returns raw pointer to Document else 0
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_JavaResult_get_1val<'local>(
-    _env: JNIEnv<'local>,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_JavaResult_get_1val<'local>(
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
-    j_result: jlong,
+    // non-null raw pointer to JavaResult wrapping *mut Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:127]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.

```suggestion
    // raw pointer to JavaResult wrapping *mut Document
```

File: jni_bindings/src/lib.rs [hunk 19]
```diff
@@ -73,159 +69,226 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_00024Comp
...
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_JavaResult_get_1error<'local>(
-    env: JNIEnv<'local>,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_JavaResult_get_1error<
+    'local,
+>(
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
-    j_result: jlong,
+    // non-null raw pointer to JavaResult
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:153]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.

```suggestion
    // raw pointer to JavaResult
```

File: jni_bindings/src/lib.rs [hunk 20]
```diff
@@ -73,159 +69,226 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_00024Comp
...
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_do_1to_1string<'local>(
-    env: JNIEnv<'local>,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_do_1to_1string<
+    'local,
+>(
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
-    dom: jlong,
+    // non-null raw pointer to Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:180]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

File: jni_bindings/src/lib.rs [hunk 21]
```diff
@@ -73,159 +69,226 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_00024Comp
...
 
 // Java side should ensure only u32 is passed as the node parameter
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_node_1to_1string<'local>(
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_node_1to_1string<
+    'local,
+>(
     mut env: JNIEnv<'local>,
     _: JClass<'local>,
+    // non-null raw pointer to Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:208]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

File: jni_bindings/src/lib.rs [hunk 22]
```diff
@@ -73,159 +69,226 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_00024Comp
...
+        }
     }
 }
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_root<'local>(
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_root<'local>(
     mut env: JNIEnv<'local>,
     _: JClass<'local>,
+    // non-null raw pointer to Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:245]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

File: jni_bindings/src/lib.rs [hunk 23]
```diff
@@ -73,159 +69,226 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_00024Comp
...
+        doc.root().as_u32() as jint
     }
 }
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node<'local>(
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node<'local>(
     mut env: JNIEnv<'local>,
     _: JClass<'local>,
+    // non-null raw pointer to Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:269]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

File: jni_bindings/src/lib.rs [hunk 24]
```diff
@@ -278,176 +341,192 @@ fn from_attr(attr: &dom::Attribute) -> Attribute {
...
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node_1leaf_1string<
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node_1leaf_1string<
     'local,
 >(
-    env: JNIEnv<'local>,
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
+    // non-null raw pointer to Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:351]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

File: jni_bindings/src/lib.rs [hunk 25]
```diff
@@ -278,176 +341,192 @@ fn from_attr(attr: &dom::Attribute) -> Attribute {
...
         }
     }
 }
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node_1type(
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node_1type(
     mut env: JNIEnv,
     _: JClass,
+    // non-null raw pointer to Node
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:383]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Node
```

File: jni_bindings/src/lib.rs [hunk 26]
```diff
@@ -278,176 +341,192 @@ fn from_attr(attr: &dom::Attribute) -> Attribute {
...
     }
 }
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node_1element(
-    env: JNIEnv,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node_1element(
+    mut env: JNIEnv,
     _: JClass,
+    // non-null raw pointer to node
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:406]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to node
```

File: jni_bindings/src/lib.rs [hunk 27]
```diff
@@ -278,176 +341,192 @@ fn from_attr(attr: &dom::Attribute) -> Attribute {
...
     }
 }
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Node_00024Element_drop(
-    env: JNIEnv,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Node_00024Element_drop(
+    mut env: JNIEnv,
     _: JClass,
+    // non-null raw pointer to Element
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:432]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Element
```

File: jni_bindings/src/lib.rs [hunk 28]
```diff
@@ -278,176 +341,192 @@ fn from_attr(attr: &dom::Attribute) -> Attribute {
...
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node_1element_1namespace<
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Node_00024Element_get_1namespace<
     'local,
 >(
-    env: JNIEnv<'local>,
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
-    element: jlong,
+    // non-null raw pointer to Element
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:454]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Element
```

File: jni_bindings/src/lib.rs [hunk 29]
```diff
@@ -278,176 +341,192 @@ fn from_attr(attr: &dom::Attribute) -> Attribute {
...
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node_1element_1tag<
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Node_00024Element_get_1tag<
     'local,
 >(
-    env: JNIEnv<'local>,
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
-    element: jlong,
+    // non-null raw pointer to Element
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:480]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Element
```

File: jni_bindings/src/lib.rs [hunk 30]
```diff
@@ -278,176 +341,192 @@ fn from_attr(attr: &dom::Attribute) -> Attribute {
...
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node_1element_1attributes<
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Node_00024Element_get_1attributes<
     'local,
 >(
-    env: JNIEnv<'local>,
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
-    element: jlong,
+    // non-null raw pointer to Element
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:506]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Element
```

File: jni_bindings/src/lib.rs [hunk 31]
```diff
@@ -457,273 +536,268 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node
...
-        }
     }
 }
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Attribute_drop(
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Attribute_drop(
     mut env: JNIEnv,
     _: JClass,
+    // non-null raw pointer to Attribute
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:550]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Attribute
```

File: jni_bindings/src/lib.rs [hunk 32]
```diff
@@ -457,273 +536,268 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node
...
 }
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Attribute_get_1name<'local>(
-    env: JNIEnv<'local>,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Attribute_get_1name<'local>(
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
-    attr: jlong,
+    // non-null raw pointer to Attribute
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:570]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Attribute
```

File: jni_bindings/src/lib.rs [hunk 33]
```diff
@@ -457,273 +536,268 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node
...
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Attribute_get_1namespace<'local>(
-    env: JNIEnv<'local>,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Attribute_get_1namespace<
+    'local,
+>(
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
-    attr: jlong,
+    // non-null raw pointer to Attribute
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:596]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Attribute
```

File: jni_bindings/src/lib.rs [hunk 34]
```diff
@@ -457,273 +536,268 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node
...
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Attribute_get_1value<'local>(
-    env: JNIEnv<'local>,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Attribute_get_1value<
+    'local,
+>(
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
-    attr: jlong,
+    // non-null raw-pointer to Attribute
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:622]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw-pointer to Attribute
```

File: jni_bindings/src/lib.rs [hunk 35]
```diff
@@ -457,273 +536,268 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node
...
 }
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1children<'local>(
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1children<
+    'local,
+>(
     mut env: JNIEnv<'local>,
     _: JClass<'local>,
+    // non-null raw pointer to Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:648]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

File: jni_bindings/src/lib.rs [hunk 36]
```diff
@@ -457,273 +536,268 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node
...
 }
 
 // Java side should ensure only u32 is passed as the node parameter
 // Note! this function returns -1 when there's no parent
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1parent(
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1parent(
     mut env: JNIEnv,
     _: JClass,
+    // non-null raw pointer to Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:680]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

File: jni_bindings/src/lib.rs [hunk 37]
```diff
@@ -457,273 +536,268 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node
...
     }
 }
 
 #[no_mangle]
-pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_merge<'local>(
-    env: JNIEnv<'local>,
+pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_merge<'local>(
+    mut env: JNIEnv<'local>,
     _: JClass<'local>,
+    // non-null raw pointer to Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:710]: The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

File: jni_bindings/src/lib.rs [hunk 38]
```diff
@@ -457,273 +536,268 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node
...
     this: jlong,
+    // non-null raw pointer to other Document
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:712]: The `non-null` can't be true or there would be no need for the `other.is_null()` check below.
```suggestion
    // raw pointer to other Document
```

File: jni_bindings/src/lib.rs [hunk 39]
```diff
@@ -457,273 +536,268 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node
...
-                        ],
-                    )
-                    .unwrap();
-                }
+    if this.is_null() || other.is_null() {
+        env.throw_new(
+            "java/lang/NullPointerException",
+            "Document::merge called with null pointer",
+        )
+        .unwrap();
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs]: This error message should be improved to tell the caller which pointer was `null`.

File: jni_bindings/src/lib.rs [hunk 40]
```diff
@@ -278,176 +341,192 @@ fn from_attr(attr: &dom::Attribute) -> Attribute {
...
+        env.throw_new(
+            "java/lang/NullPointerException",
+            "Document::get_node_element called with `node` as null pointer",
+        )
+        .unwrap();
+
+        0
+    } else {
+        let node = &*node;
+        let element = Box::new(node.data.element.clone());
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:422]: The previous version did not clone the element.  This changes the semantics of the function.  Was this intentional?

**Review by KronicDeth — CHANGES_REQUESTED** [review]

File: jni_bindings/src/lib.rs (hunk 5 above)
Comment (Bajix) [reply jni_bindings/src/lib.rs:31]: Those changes are as a better means to prevent undefined behavior and to gracefully handle this exception because catch_unwind manages panics and not undefined behavior. If a null pointer is passed, this still will throw an exception, so it's documented this way because what is expected in the safety contract is a valid pointer.

File: core/src/main/java/org/phoenixframework/liveview/lib/Document.kt (hunk 6 above)
Comment (Bajix) [reply core/src/main/java/org/phoenixframework/liveview/lib/Document.kt:133]: Drop will never be called twice because it's private and finalize is by-design called at most once. The previous version of this was creating many Documents all with the same underlying native object pointer leading to each freeing the same native pointer causing the double free scenario which is now sidestepped by using asBorrow for Documents passed into callbacks to skip drop as an alternative to borrowing over FFI. I do have a borrow over FFI alternative but it wasn't stable when we tested and I changed course

File: jni_bindings/src/lib.rs (hunk 40 above)
Comment (Bajix) [reply jni_bindings/src/lib.rs:422]: I don't think it makes sense for Element and Attribute to remain being `Copy` in core so I was making this change as though that were changed

File: core/build.gradle (hunk 2 above)
Comment (Bajix) [reply core/build.gradle:69]: Yea Nelson did a great job with the build.gradle changes overall; it was really not obvious how to fix this linking issue

File: jni_bindings/src/lib.rs (hunk 36 above)
Comment (Bajix) [reply jni_bindings/src/lib.rs:680]: The rationale for documenting it this way is that it's an exception for a null pointer to be passed. The null check is to manage this exception in a way that is sound and doesn't rely on catch_rewind

File: core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt (hunk 13 above)
Comment (Bajix) [reply core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt]: I'm confused the commit suggestion interface says no changes were made

File: core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt (hunk 14 above)
Comment (Bajix) [reply core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt:38]: This test was to create a scenario in which a double free would occur without the asBorrow change. Merge is infallible

File: core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt (hunk 13 above)
Comment (KronicDeth) [reply core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt]: Redid it, it supposed to be to just delete the generated comment because it doesn't apply anymore.

File: core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt (hunk 14 above)
Comment (KronicDeth) [reply core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt:38]: So the test segfaults if the bug still exists?  Can we add a comment about that?

File: jni_bindings/src/lib.rs [hunk 41]
```diff
@@ -457,273 +536,268 @@ pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_get_1node
...
-                }
+    if this.is_null() || other.is_null() {
+        env.throw_new(
+            "java/lang/NullPointerException",
+            "Document::merge called with null pointer",
+        )
+        .unwrap();
+
+        return;
+    }
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs]: Here's a suggestion for a more specific error message

```suggestion
    let this_null = this.is_null();
    let other_null = other.is_null();
    
    if this_null() || other_null() {
        let message = String::new("Document::merged called with ");
        
        if this_null {
           message.push_str("null this pointer");
          
           if other_null {
              message.push_str(" and ");
            }
        }
        
        if other_null {
            message.push_str("null other pointer");
        }
        
        env.throw_new(
            "java/lang/NullPointerException",
            message,
        )
        .unwrap();

        return;
    }
```

**Review by KronicDeth — CHANGES_REQUESTED** [review]

File: jni_bindings/src/lib.rs [hunk 42]
```diff
@@ -716,11 +718,15 @@ pub unsafe extern "system" fn Java_org_phoenixframework_liveview_lib_Document_me
     let other = other as *mut Document;
 
     if this.is_null() || other.is_null() {
-        env.throw_new(
-            "java/lang/NullPointerException",
-            "Document::merge called with null pointer",
-        )
-        .unwrap();
+        let message = match (this.is_null(), other.is_null()) {
```
Comment (KronicDeth) [inline jni_bindings/src/lib.rs:721]: Using a `match` was the other way I considered doing it.  I wasn't sure if having static strs was more important or 1 path for each part of the message.

**Review by KronicDeth — APPROVED** [review]

File: jni_bindings/src/lib.rs (hunk 42 above)
Comment (Bajix) [reply jni_bindings/src/lib.rs:721]: Both ways work this just avoids the heap allocation overhead

File: core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt (hunk 14 above)
Comment (Bajix) [reply core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt:38]: Sure I'll add
